/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Appointment': { kind: 'OBJECT'; name: 'Appointment'; fields: { 'availability': { name: 'availability'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'CounselorAvailability'; ofType: null; }; } }; 'availableAt': { name: 'availableAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'counselor': { name: 'counselor'; type: { kind: 'OBJECT'; name: 'Counselor'; ofType: null; } }; 'counselorId': { name: 'counselorId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'endedAt': { name: 'endedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'scheduledEnd': { name: 'scheduledEnd'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'scheduledStart': { name: 'scheduledStart'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'AppointmentStatus'; ofType: null; }; } }; }; };
    'AppointmentStatus': { name: 'AppointmentStatus'; enumValues: 'OPEN' | 'WAITING' | 'ACTIVE' | 'ENDED'; };
    'Boolean': unknown;
    'ChimeAttendee': { kind: 'OBJECT'; name: 'ChimeAttendee'; fields: { 'attendeeId': { name: 'attendeeId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'externalUserId': { name: 'externalUserId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'joinToken': { name: 'joinToken'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ChimeAttendeeInfo': { kind: 'OBJECT'; name: 'ChimeAttendeeInfo'; fields: { 'attendeeId': { name: 'attendeeId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'externalUserId': { name: 'externalUserId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ChimeMediaPlacement': { kind: 'OBJECT'; name: 'ChimeMediaPlacement'; fields: { 'audioFallbackUrl': { name: 'audioFallbackUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'audioHostUrl': { name: 'audioHostUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'signalingUrl': { name: 'signalingUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'turnControlUrl': { name: 'turnControlUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ChimeMeeting': { kind: 'OBJECT'; name: 'ChimeMeeting'; fields: { 'mediaPlacement': { name: 'mediaPlacement'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChimeMediaPlacement'; ofType: null; }; } }; 'mediaRegion': { name: 'mediaRegion'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'meetingId': { name: 'meetingId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ChimeSessionStatus': { kind: 'OBJECT'; name: 'ChimeSessionStatus'; fields: { 'appointmentId': { name: 'appointmentId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'attendees': { name: 'attendees'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChimeAttendeeInfo'; ofType: null; }; }; } }; 'chimeMeetingId': { name: 'chimeMeetingId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'sessionId': { name: 'sessionId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'sessionStatus': { name: 'sessionStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'SessionStatus'; ofType: null; }; } }; 'talkerId': { name: 'talkerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Counselor': { kind: 'OBJECT'; name: 'Counselor'; fields: { 'experienceYears': { name: 'experienceYears'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'photoUrl': { name: 'photoUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'rating': { name: 'rating'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'specialty': { name: 'specialty'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'CounselorAvailability': { name: 'CounselorAvailability'; enumValues: 'AVAILABLE' | 'SOON' | 'LATER' | 'OFFLINE'; };
    'CounselorStats': { kind: 'OBJECT'; name: 'CounselorStats'; fields: { 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Float': unknown;
    'ID': unknown;
    'Int': unknown;
    'JoinChimeMeetingResult': { kind: 'OBJECT'; name: 'JoinChimeMeetingResult'; fields: { 'attendee': { name: 'attendee'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChimeAttendee'; ofType: null; }; } }; 'meeting': { name: 'meeting'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChimeMeeting'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'createAppointment': { name: 'createAppointment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; } }; 'createChimeAttendee': { name: 'createChimeAttendee'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChimeAttendee'; ofType: null; }; } }; 'createChimeMeeting': { name: 'createChimeMeeting'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChimeMeeting'; ofType: null; }; } }; 'deleteAppointment': { name: 'deleteAppointment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'endAppointment': { name: 'endAppointment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; } }; 'joinAppointment': { name: 'joinAppointment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; } }; 'joinChimeMeeting': { name: 'joinChimeMeeting'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'JoinChimeMeetingResult'; ofType: null; }; } }; 'leaveAppointment': { name: 'leaveAppointment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; } }; 'seedDatabase': { name: 'seedDatabase'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SeedResult'; ofType: null; }; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'appointment': { name: 'appointment'; type: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; } }; 'appointments': { name: 'appointments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; }; }; } }; 'chimeStatus': { name: 'chimeStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChimeSessionStatus'; ofType: null; }; }; }; } }; 'counselor': { name: 'counselor'; type: { kind: 'OBJECT'; name: 'Counselor'; ofType: null; } }; 'counselorAppointment': { name: 'counselorAppointment'; type: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; } }; 'counselorStats': { name: 'counselorStats'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CounselorStats'; ofType: null; }; } }; 'counselors': { name: 'counselors'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Counselor'; ofType: null; }; }; }; } }; 'openAppointments': { name: 'openAppointments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; }; }; } }; 'sessions': { name: 'sessions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Session'; ofType: null; }; }; }; } }; 'talkers': { name: 'talkers'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Talker'; ofType: null; }; }; }; } }; }; };
    'SeedResult': { kind: 'OBJECT'; name: 'SeedResult'; fields: { 'seeded': { name: 'seeded'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Session': { kind: 'OBJECT'; name: 'Session'; fields: { 'appointmentId': { name: 'appointmentId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'chimeMeetingId': { name: 'chimeMeetingId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'endedAt': { name: 'endedAt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'startedAt': { name: 'startedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'SessionStatus'; ofType: null; }; } }; 'talkerId': { name: 'talkerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'SessionStatus': { name: 'SessionStatus'; enumValues: 'ACTIVE' | 'ENDED'; };
    'String': unknown;
    'Talker': { kind: 'OBJECT'; name: 'Talker'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'photoUrl': { name: 'photoUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}